### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by JustinDrake** [alinush/libpolycrypto#2]
The writeup [here](https://alinush.github.io/2020/03/12/scalable-bls-threshold-signatures.html) states:

> Our work also address how to scale the necessary distributed key generation (DKG) protocol needed to bootstrap a BLS threshold signature scheme. We present these results in another post.

Unfortunately the link https://alinush.github.io/2020/03/12/2020/03/12/towards-scalable-vss.html to the other post is a 404.

**Comment by alinush** [comment]
Thank you Justin! Fixed.
